# Generated by Django 2.1.2 on 2019-07-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('processador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('qtd_memoria', models.PositiveSmallIntegerField()),
                ('qtd_ram', models.PositiveSmallIntegerField()),
                ('video_integrado', models.BooleanField()),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processador.Processador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto')),
            ],
        ),
    ]
